#!/bin/bash

# Define project name
PROJECT_DIR="Verification_Assignment"

# Create Project Directory
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"
echo "Created Project Directory: $PROJECT_DIR"

# ---------------------------------------------------------
# 1. Create Directories
# ---------------------------------------------------------
mkdir -p 1_rtl
mkdir -p 2_simple_tb
mkdir -p 3_random_tb
mkdir -p 4_assertions
mkdir -p 5_harm
mkdir -p 6_traces
mkdir -p 7_scripts

echo "Created subdirectories: 1_rtl, 2_simple_tb, 3_random_tb, 4_assertions, 5_harm, 6_traces, 7_scripts"

# ---------------------------------------------------------
# 2. Create Placeholder Files
# ---------------------------------------------------------

# 1_rtl: The Vending Machine Design
touch 1_rtl/vending_machine.sv

# 2_simple_tb: Verilog-style testbench
touch 2_simple_tb/simple_tb.sv

# 3_random_tb: Constrained random testbench files
# Keeping it simple: one top file or split slightly for clarity
touch 3_random_tb/random_tb_top.sv
touch 3_random_tb/transaction.sv
touch 3_random_tb/generator.sv
touch 3_random_tb/interface.sv

# 4_assertions: Assertions and binding file
touch 4_assertions/assertions.sv
touch 4_assertions/bind.sv

# 5_harm: Configuration file for HARM
touch 5_harm/conf.xml

echo "Created source file placeholders in respective directories."

# ---------------------------------------------------------
# 3. Create Runner Scripts (in 7_scripts)
# ---------------------------------------------------------
# We use relative paths assuming the script is run from inside 7_scripts

# --- Script 1: Run Simple TB ---
cat <<EOT > 7_scripts/run_simple.sh
#!/bin/bash
# Clean previous work
rm -rf work
vlib work

# Compile RTL and Simple TB
vlog ../1_rtl/vending_machine.sv
vlog ../2_simple_tb/simple_tb.sv

# Run Simulation (batch mode)
# Generates vcd, runs all, and quits
vsim -c -voptargs=+acc work.simple_tb -do "vcd file simple.vcd; vcd add -r /*; run -all; quit"

# Move traces to 6_traces
mv simple.vcd ../6_traces/simple_tb.vcd
echo "Trace moved to ../6_traces/simple_tb.vcd"
EOT

# --- Script 2: Run Random TB ---
cat <<EOT > 7_scripts/run_random.sh
#!/bin/bash
rm -rf work
vlib work

# Compile RTL and Random TB
vlog ../1_rtl/vending_machine.sv
vlog ../3_random_tb/*.sv

# Run Simulation
vsim -c -voptargs=+acc work.random_tb_top -do "vcd file random.vcd; vcd add -r /*; run -all; quit"

# Move traces
mv random.vcd ../6_traces/random_tb.vcd
echo "Trace moved to ../6_traces/random_tb.vcd"
EOT

# --- Script 3: Run Assertions ---
cat <<EOT > 7_scripts/run_assertions.sh
#!/bin/bash
rm -rf work
vlib work

# Compile RTL, Assertions, Bind file, and Random TB (reused for driving inputs)
vlog ../1_rtl/vending_machine.sv
vlog ../4_assertions/assertions.sv
vlog ../4_assertions/bind.sv
vlog ../3_random_tb/*.sv

# Run Simulation with Assertions enabled
vsim -c -assertdebug -voptargs=+acc work.random_tb_top -do "vcd file assertions.vcd; vcd add -r /*; run -all; quit"

# Move traces
mv assertions.vcd ../6_traces/assertions.vcd
echo "Trace moved to ../6_traces/assertions.vcd"
EOT

# --- Script 4: Run HARM ---
cat <<EOT > 7_scripts/run_harm.sh
#!/bin/bash

# HARM usually requires a VCD file and a config file.
# We assume the VCD is already generated by the previous steps (e.g., random_tb).
# We run HARM pointing to that VCD and the config.

cd ../5_harm
# Replace 'harm' with the actual path to your HARM executable if needed
harm --conf conf.xml --vcd ../6_traces/random_tb.vcd --clk clk

# If HARM generates output files, we can move them or keep them here
echo "HARM mining complete."
EOT

# Make scripts executable
chmod +x 7_scripts/*.sh

echo "Created runner scripts in 7_scripts and made them executable."
echo "Project setup complete."